# OBJECT_FILES = triangle.o
# CXX = g++
# CXXFLAGS = -Wall

# LIB_PATH = -L /usr/local/lib/
# LIB = simple2d

# INC_PATH = -I /usr/local/include/


# TARGET = drawer
default: main

main:
	g++ main_drawer.cpp `simple2d --libs` -o drawer

# $(TARGET): $(OBJECT_FILES)
# 	$(CXX) $(CFLAGS) $(INC_PATH) $(LIB_PATH) $(OBJECT_FILES) -o $(TARGET)

# triangle.o: triangle.c
# 	$(CXX) $(CFLAGS) $(INC_PATH) $(LIB_PATH) -c triangle.c

# clean:
# 	rm -f $(TARGET) $(OBJECT_FILES) 